import { cp, mkdir, rm, readFile, writeFile } from 'node:fs/promises';

const OUT = 'public/_ds';
await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });
await cp('_ds/tokens', `${OUT}/tokens`, { recursive: true });
await cp('_ds/assets', `${OUT}/assets`, { recursive: true });

// --- token bundle -----------------------------------------------------------
//
// Every page linked all ten token files individually, which is ten
// render-blocking requests per page load for ten files that never change
// independently of each other — they are one vendored export. This
// concatenates them, in the cascade order Base.astro already used, into a
// single stylesheet the layout links instead.
//
// The individual files are still copied above and still served, so anything
// that references one by name (a kit page under _ds/, a bookmarked URL) keeps
// working. This only adds a bundle; it removes nothing.
//
// _ds/ itself is never written to — the bundle is a build artifact under
// public/, the same as the copies above.
const TOKENS = [
  'fonts',
  'colors',
  'themes',
  'typography',
  'spacing',
  'shape',
  'marketing',
  'responsive',
  'motion',
  'base',
];

const parts = [];
// CSS requires every @import to precede all other rules, so they are hoisted
// rather than left wherever they fall in the concatenation. Today the only one
// is fonts.css's Google Fonts import, and fonts.css is already first — this
// keeps the bundle valid if that ever stops being true, instead of silently
// dropping an import and losing a typeface.
const imports = [];

for (const name of TOKENS) {
  const css = await readFile(`_ds/tokens/${name}.css`, 'utf8');
  // `.*;` greedy to the LAST semicolon on the line, not `[^;]+;` to the first
  // — the Google Fonts URL carries semicolons of its own inside its weight
  // axes (`wght@400;500;600;700`), so a non-greedy match stopped mid-URL,
  // failed the end-of-line anchor and hoisted nothing.
  const stripped = css.replace(/^[\t ]*@import\b.*;[\t ]*$/gm, (m) => {
    imports.push(m.trim());
    return '';
  });
  parts.push(`/* --- _ds/tokens/${name}.css --- */\n${stripped.trim()}\n`);
}

const bundle = [
  '/* Generated by scripts/sync-ds.js. Do not edit — edit _ds/tokens/*.css',
  '   and re-run `npm run sync:ds`. Source order is Base.astro\'s cascade order. */',
  ...imports,
  '',
  ...parts,
].join('\n');

await writeFile(`${OUT}/tokens.css`, bundle);

console.log(`synced _ds → public/_ds (bundled ${TOKENS.length} token files → tokens.css)`);
