import { experimental_AstroContainer as AstroContainer } from 'astro/container';
import { readFileSync, existsSync } from 'node:fs';
import { expect, test } from 'vitest';
import Base from '../../src/layouts/Base.astro';

const render = () =>
  AstroContainer.create().then((c) =>
    c.renderToString(Base, {
      props: {
        title: 'Manuva — MRP for Shopify manufacturers',
        description: 'Inventory, BOMs, work orders and stock control.',
        canonical: 'https://manuva.app/',
      },
      slots: { default: '<p>body content</p>' },
    }),
  );

// The ten token files used to be linked individually — ten render-blocking
// requests per page for ten files that only ever change together. The layout
// links one bundle now, generated by scripts/sync-ds.js. The cascade order
// still matters exactly as much as it did, so it is still asserted; it just
// moved from the <head> to the generated file.
const TOKEN_ORDER = [
  'fonts', 'colors', 'themes', 'typography', 'spacing',
  'shape', 'marketing', 'responsive', 'motion', 'base',
];

test('links the token bundle, not ten separate token files', async () => {
  const html = await render();
  expect(html).toMatch(/_ds\/tokens\.css/);
  expect(
    [...html.matchAll(/_ds\/tokens\/([a-z-]+\.css)/g)],
    'individual token files should no longer be linked one at a time',
  ).toEqual([]);
});

test('the bundle concatenates every token file in styles.css order', () => {
  const bundle = readFileSync('dist/_ds/tokens.css', 'utf8');
  const order = [...bundle.matchAll(/--- _ds\/tokens\/([a-z-]+)\.css ---/g)].map((m) => m[1]);
  expect(order).toEqual(TOKEN_ORDER);
});

test('the bundle hoists @import above every rule, as CSS requires', () => {
  const bundle = readFileSync('dist/_ds/tokens.css', 'utf8');
  const imports = [...bundle.matchAll(/^[\t ]*@import\b/gm)];
  // Today there is exactly one: fonts.css's Google Fonts import. If it ever
  // stops being hoisted the browser drops it silently and the site loses its
  // display face, which is the kind of failure nothing else here would catch.
  expect(imports.length).toBeGreaterThan(0);
  const firstRule = bundle.search(/^[\t ]*[.:@a-zA-Z[*]/m);
  for (const m of imports) {
    expect(m.index, '@import must precede every rule').toBeLessThanOrEqual(
      bundle.indexOf('/* --- _ds/tokens/'),
    );
  }
  expect(firstRule).toBeGreaterThanOrEqual(0);
});

test('fonts.css stays individually swappable behind the bundle', () => {
  // MVBOLD-3 replaces fonts.css with a self-hosted variant. The bundle must
  // not make that harder: sync-ds.js reads _ds/tokens/*.css and regenerates,
  // so swapping the source file is still the whole change.
  const bundle = readFileSync('dist/_ds/tokens.css', 'utf8');
  expect(bundle).toContain('/* --- _ds/tokens/fonts.css --- */');
  expect(existsSync('dist/_ds/tokens/fonts.css'), 'individual files still served').toBe(true);
});

test('never links the design system aggregate entry point', async () => {
  // _ds/styles.css is the design system's OWN aggregate, which pulls in things
  // this site does not want. The bundle above is ours, built from the ten
  // token files only.
  const html = await render();
  expect(html).not.toMatch(/_ds\/styles\.css/);
});

test('emits title, description and canonical', async () => {
  const html = await render();
  expect(html).toContain('<title>Manuva — MRP for Shopify manufacturers</title>');
  expect(html).toContain('name="description" content="Inventory, BOMs, work orders and stock control."');
  expect(html).toContain('rel="canonical" href="https://manuva.app/"');
});

test('canonical never carries a trailing slash except on root', async () => {
  const c = await AstroContainer.create();
  const html = await c.renderToString(Base, {
    props: { title: 't', description: 'd', canonical: 'https://manuva.app/features' },
    slots: { default: '<p>x</p>' },
  });
  expect(html).toContain('href="https://manuva.app/features"');
  expect(html).not.toContain('href="https://manuva.app/features/"');
});

test('provides a skip link as the first focusable element', async () => {
  const html = await render();
  expect(html).toMatch(/<a[^>]+href="#main"[^>]*>\s*Skip to content\s*<\/a>/);
});

// Task 10 fix round 1: a first pass wired twitter:title/twitter:description
// unconditionally off ogDescription's own default (= the long `description`),
// which silently emitted the long meta description as the Twitter card body
// on / and /pricing — both real pages carry a shorter Twitter variant Base
// had never read before. twitterDescription has no fallback of its own on
// purpose: omit it and the whole triple is omitted, exactly like before this
// file grew a Twitter card at all.
//
// Fix round 2: twitter:card was left unconditional while title/description
// were gated on twitterDescription, so a page that omits it (as /about,
// /privacy, /terms are likely to, next) would ship a lone twitter:card with
// no title or body — a half-populated card. All three tags are now gated
// together.
test('omits the entire twitter:card/title/description triple when twitterDescription is not supplied', async () => {
  const html = await render();
  expect(html).not.toContain('name="twitter:card"');
  expect(html).not.toContain('name="twitter:title"');
  expect(html).not.toContain('name="twitter:description"');
});

test('emits twitter:card/title/description together only when twitterDescription is explicitly supplied, using its own value', async () => {
  const c = await AstroContainer.create();
  const html = await c.renderToString(Base, {
    props: {
      title: 'Manuva — MRP for Shopify manufacturers',
      description: 'The long meta description, never the Twitter one.',
      canonical: 'https://manuva.app/',
      twitterDescription: 'The short Twitter variant.',
    },
    slots: { default: '<p>body content</p>' },
  });
  expect(html).toContain('name="twitter:card" content="summary_large_image"');
  expect(html).toContain('name="twitter:title" content="Manuva — MRP for Shopify manufacturers"');
  expect(html).toContain('name="twitter:description" content="The short Twitter variant."');
  expect(html).not.toContain('name="twitter:description" content="The long meta description, never the Twitter one."');
});

test('og:description defaults to `description` but og:type defaults to "website", both overridable', async () => {
  const c = await AstroContainer.create();
  const defaultHtml = await c.renderToString(Base, {
    props: { title: 't', description: 'd', canonical: 'https://manuva.app/' },
    slots: { default: '<p>x</p>' },
  });
  expect(defaultHtml).toContain('property="og:type" content="website"');
  expect(defaultHtml).toContain('property="og:description" content="d"');

  const overriddenHtml = await c.renderToString(Base, {
    props: {
      title: 't', description: 'd', canonical: 'https://manuva.app/',
      ogDescription: 'shorter og variant', ogType: 'article',
    },
    slots: { default: '<p>x</p>' },
  });
  expect(overriddenHtml).toContain('property="og:type" content="article"');
  expect(overriddenHtml).toContain('property="og:description" content="shorter og variant"');
});
